/**
 * The People tab on a running campaign and the person drawer (Relay P5): the
 * list, its filters, and everything the drawer says about one person.
 */
export const outreachPeopleCopy = {
  tabsLabel: "Campaign views",
  tabOverview: "Overview",
  tabPeople: "People",

  listLabel: "People",
  filterStatus: "Status",
  filterAll: "Everyone",
  filterDue: "Due today or overdue",
  search: "Search by name or company",
  searchPlaceholder: "Name or company",
  shown: "shown",
  of: "of",
  nobody: "Nobody matches these filters.",
  clearFilters: "Clear filters",
  paused: "This campaign is paused. Nothing is due until you resume it.",

  status: {
    not_started: "Not started",
    in_sequence: "In sequence",
    replied: "Replied",
    meeting: "Meeting",
    closed: "Closed",
  },
  progress: "steps done",
  next: "Next",
  nothingDue: "Nothing due",
  overdue: "Overdue",
  started: "Started",
  linkedin: "LinkedIn",
  /** Read after the LinkedIn link, for a screen reader: it opens elsewhere. */
  opensNewTab: "(opens in a new tab)",
  openPerson: "Open",

  drawerLabel: "Person",
  close: "Close",
  noEmail: "No email",
  phone: "Phone",
  addPhone: "Add phone",
  editPhone: "Change",
  savePhone: "Save",
  saving: "Saving",
  cancel: "Cancel",
  meetingBooked: "Meeting booked",
  notInterested: "Not interested",
  wrongPerson: "Wrong person",
  outcomeLabel: "Close this person",
  meetingOn: "Meeting booked on",
  closedAs: "Closed as",
  outcome: {
    not_interested: "Not interested",
    wrong_person: "Wrong person",
    bounced: "Email bounced",
    closed: "Closed",
  },
  notFound: "That person isn't on this campaign any more.",

  sequenceLabel: "Sequence",
  nextBadge: "Next",
  channel: {
    email: "Email",
    connect: "LinkedIn",
    dm: "LinkedIn",
    call: "Call",
  },
  step: {
    email1: "Email 1",
    li_connect: "Connect note",
    call1: "Call 1",
    email2: "Email 2",
    li_dm: "LinkedIn message",
    call2: "Call 2",
    li_dm2: "LinkedIn follow-up",
    breakup: "Last email",
  },
  stepState: {
    planned: "Planned",
    due: "Due",
    overdue: "Overdue",
    waiting: "Waiting",
    paused: "Paused",
    done: "Done",
    skipped: "Skipped",
  },
  waitingFor: {
    accepted: "Waiting for accept",
    li_dm_sent: "Waiting for the first message",
  },
  due: "Due",
  sentOn: "Sent",
  calledOn: "Called",
  response: {
    accepted: "Accepted",
    declined: "Declined",
    replied: "Replied",
    bounced: "Bounced",
  },
  showDraft: "Show",
  hideDraft: "Hide",

  noDraft: "No draft for this step yet.",
  draftApproved: "Approved",
  draftRejected: "Rejected",
  redrafting: "Relay is writing this one again.",
  notWritten: "Relay couldn't write this one.",
  heldForYou: "Held for you: the checks found something to look at.",
  tryAgain: "Try again",
  tryingAgain: "Asking",
  triedEnough: "Relay has tried three times. Write this one yourself.",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Couldn't copy. Select the text instead.",

  markSent: "Mark sent",
  markAccepted: "Accepted",
  markDeclined: "Declined",
  markReplied: "Replied",
  markBounced: "Bounced",
  markCallDone: "Mark call done",
  approveFirst: "Approve it before you mark it sent.",

  callResultLabel: "How did it go?",
  callResult: {
    spoke: "Spoke",
    voicemail: "Voicemail",
    no_answer: "No answer",
    wrong_number: "Wrong number",
  },
  callNote: "Note (optional)",
  saveCall: "Save call",

  notesLabel: "Notes",
  noNotes: "No notes yet.",
  addNote: "Add note",
  noteField: "New note",

  activityLabel: "Activity",
  noActivity: "Nothing recorded yet.",
  undo: "Undo",
  undoing: "Undoing",
  activity: {
    sent: "sent",
    done: "made",
    accepted: "accepted",
    declined: "declined",
    replied: "replied",
    bounced: "bounced",
    note: "Note added",
    meeting: "Meeting booked",
    outcome: "Closed",
  },

  cannotChange: "That didn't work. Refresh the page and try again.",
} as const;
