/**
 * "What Relay learned": the research view of a campaign (task 19).
 *
 * One long page in eleven parts, drawn from the stored research. Everything a
 * rep reads here that research did not write is in this file; research's own
 * words reach the screen as research wrote them.
 */
export const researchCopy = {
  title: "What Relay learned",
  /** The Overview's one way in. */
  openLink: "What Relay learned →",
  back: "← Back to the campaign",
  metaSource: "source",
  metaSources: "sources",
  metaResearched: "researched",
  jumpTo: "Jump to",
  inThisResearch: "In this research",
  jumpToSection: "Jump to section",
  chooseSection: "Choose a section",
  expandAll: "Expand all",
  collapseAll: "Collapse all",
  /** A closed part's way in: "View" and what opens. */
  view: "View",
  viewLabels: {
    market: "the market and timeline",
    who: "who to target",
    pains: "pains and buyer language",
    say: "what to say",
    prove: "answers, proof and what not to claim",
    competition: "the competition",
    companies: "example companies",
    gather: "where buyers gather",
    contact: "contact rules",
    gaps: "unresolved research",
    sources: "the sources",
  },
  /**
   * A closed part's preview: counts of what it holds, each as one and many,
   * with the number put in front at the call site.
   */
  preview: {
    moments: ["dated moment", "dated moments"],
    comingUp: "coming up",
    nextOn: "the next on",
    segments: ["part of the market", "parts of the market"],
    groups: ["kind of buyer", "kinds of buyer"],
    notAFit: ["kind of firm that is not a fit", "kinds of firm that are not a fit"],
    boundaries: ["hard boundary", "hard boundaries"],
    pains: ["pain", "pains"],
    across: "across",
    buyerPhrases: ["phrase in buyers' own words", "phrases in buyers' own words"],
    fromOthers: "from others",
    angles: ["angle", "angles"],
    doDont: ["do and don't", "dos and don'ts"],
    words: ["word to use", "words to use"],
    answered: ["pain answered", "pains answered"],
    partly: "partly answered",
    cantAnswer: "the product can't answer",
    objections: ["objection", "objections"],
    dontClaim: ["thing not to claim", "things not to claim"],
    competitors: ["competitor researched", "competitors researched"],
    prices: ["price compared", "prices compared"],
    doNothing: "plus what happens if they do nothing",
    firms: ["example firm", "example firms"],
    sizeUnknown: "with size not known",
    kinds: {
      event: ["event", "events"],
      association: ["association or body", "associations and bodies"],
      publication: ["publication", "publications"],
      community: ["community", "communities"],
      "review-site": ["review site", "review sites"],
      press: ["press title", "press titles"],
    },
    toolPlaces: ["place they look for tools", "places they look for tools"],
    rules: ["rule", "rules"],
    and: "and",
    restrict: ["restricts a channel", "restrict a channel"],
    gaps: ["gap", "gaps"],
    contradictions: ["contradiction", "contradictions"],
    questions: ["question worth asking", "questions worth asking"],
    sources: ["source", "sources"],
    readOn: "read",
    partlyUnwritten: "some of this part was not written",
  },

  /** The eleven parts, in page order. */
  parts: {
    market: "The market and why now",
    who: "Who to target",
    pains: "Pains and buyer language",
    say: "What to say",
    prove: "What we can answer and prove",
    competition: "Competition",
    companies: "Example companies and targeting",
    gather: "Where buyers gather",
    contact: "Contact rules",
    gaps: "Gaps and contradictions",
    sources: "Sources",
  },
  /** The same parts, short, for the Jump to links. */
  jump: {
    market: "Market and why now",
    who: "Who to target",
    pains: "Pains and language",
    say: "What to say",
    prove: "Answer and prove",
    competition: "Competition",
    companies: "Example companies",
    gather: "Where buyers gather",
    contact: "Contact rules",
    gaps: "Gaps",
    sources: "Sources",
  },
  /**
   * Research sometimes names one of its own parts in a sentence ("the contact
   * rules in m12"). The name is replaced with the part of this page that
   * shows it, so no internal name reaches a rep.
   */
  partRefs: {
    m00: "Who to target",
    m01: "The market and why now",
    m02: "Competition",
    m03: "Who to target",
    m04: "Example companies and targeting",
    m05: "Pains and buyer language",
    m06: "Pains and buyer language",
    m07: "What we can answer and prove",
    m08: "Who to target",
    m09: "What to say",
    m10: "Where buyers gather",
    m11: "What we can answer and prove",
    m12: "Contact rules",
    m13: "The market and why now",
    m14: "What changed since the last research",
    m15: "What we can answer and prove",
    m16: "Who to target",
    m17: "Gaps and contradictions",
    m18: "Gaps and contradictions",
    m19: "Sources",
  },
  /** What a reference to research's facts file reads as: the facts are Relay's, the file and its ids are not a rep's. */
  factsRef: "Relay's facts about the product",
  factRef: "a fact about the product",
  /** Research's own words for a kind of buyer and a part in the buying, as the rest of Relay says them. */
  kindOfBuyer: "kind of buyer",
  kindsOfBuyer: "kinds of buyer",
  role: "role",
  roles: "roles",
  unwrittenAll: "Relay ran out of time before it wrote this part.",
  unwrittenSome: "Relay ran out of time before it wrote some of this part:",
  nothingHere: "Research found nothing for this part.",
  show: "Show",
  hide: "Hide",

  // The market and why now
  theCase: "Why this market",
  timelineLabel: "Timeline",
  alreadyHappened: "Already happened",
  comingUp: "Coming up",
  asOf: "As of",
  asOfTail: "when Relay researched this.",
  alsoReported: "also reported that day",
  alsoExpected: "Also expected",
  undated: "Date not given",
  segmentsLabel: "Parts of the market",
  fit: { HIGH: "Strong fit", MEDIUM: "Some fit", LOW: "Weak fit", OUT: "Out of scope" },
  segmentCount: "How many:",
  sizeLabel: "How big it is",
  measuresLabel: "what is published about it",
  bodiesLabel: "who shapes this market",

  // Who to target
  ranked: "Ranked",
  rankedOf: "of",
  dominantPain: "The pain that dominates",
  involved: "Who is involved",
  needs: "Needs:",
  deal: "what a deal might look like",
  dealFields: { seatRange: "Seats", plan: "Plan", yearOneValue: "First year", salesCycle: "How long it takes", budgetLine: "Whose budget" },
  idealCompany: "The ideal company",
  idealBuyer: "The ideal buyer",
  notAFit: "Not a fit",
  boundariesLabel: "Hard boundaries",
  boundariesNote: "Research held the whole market to these. Each is shown once.",
  boundaryLabels: { geography: "Where", size: "Size", sectorsIn: "In scope", sectorsOut: "Out of scope", firmsOut: "Firms to leave out", other: "Also" },
  groupBoundaries: "Also for",

  // Pains and buyer language
  painsLabel: "Pains, most acute first",
  buyerCount: "in buyers' own words",
  otherCount: "from others",
  otherVoicesLabel: "Not buyers' words",
  voices: {
    practitioner: "A practitioner",
    "firm-document": "A firm's own document",
    "representative-body": "A trade or professional body",
    regulator: "The regulator",
    adviser: "An adviser or consultant",
    vendor: "A supplier",
  },

  // What to say
  position: "How to position it",
  anglesLabel: "Angles, ranked",
  leadWith: "Lead with this",
  suits: "Suits",
  doDontLabel: "Do and don't",
  doLabel: "Do:",
  dontLabel: "Don't:",
  whyLabel: "Why:",
  verbatimLabel: "Lines from the sources",
  vocabularyLabel: "Words to use",

  // What we can answer and prove
  answersLabel: "How the product answers each pain",
  strength: { direct: "Answers it", partial: "Partly answers it" },
  seeLimits: "limits under Don't claim",
  painWord: "Pain",
  unansweredLabel: "Pains the product can't answer",
  objectionsLabel: "Objections and answers",
  noAnswer: "No answer Relay could ground in what the product does today.",
  notToday: "Not available today",
  proofLabel: "What you can say",
  proofNote: "How to say it:",
  dontClaimLabel: "Don't claim",
  dontClaimNote: "Everything research says not to claim, in one place.",
  dontLead: "Don't lead with",
  dontProduct: "What the product doesn't do",
  dontBrand: "How not to say it",
  dontImply: "Don't imply",
  dontProof: "Proof you can't use",
  forLabel: "For",
  otherPains: "Pains Relay couldn't tie to a group",

  // Competition
  viewLabel: "Where the product stands",
  doNothingLabel: "If they do nothing",
  priceLabel: "Price:",
  notPublished: "Not published",
  strengthsLabel: "strengths and weaknesses",
  strongAt: "Strong at",
  weakAt: "Weak at",
  recentMoves: "Recent moves",
  pricesLabel: "prices side by side",
  priceCols: { name: "Offer", price: "Price", minimum: "Minimum", commitment: "Commitment" },
  adjacentLabel: "also in the picture",

  // Example companies and targeting
  fitsBecause: "Why it fits",
  sizeFrom: "Size from",
  findMore: "how to find more like these",
  recipeSizeLabel: "Size",
  titlesLabel: "Titles to reach",
  excludeLabel: "Titles to leave out",
  signsLabel: "Signs a firm is ready",
  signStrength: { HOT: "Strong sign", WARM: "Worth watching" },
  whereToLook: "Where to look:",
  listSourcesLabel: "Lists to start from",

  // Where buyers gather
  kinds: {
    event: "Events",
    association: "Associations and bodies",
    publication: "Publications",
    community: "Communities",
    "review-site": "Review and comparison sites",
    press: "Press",
  },
  onTimeline: "on the timeline",
  discoveryLabel: "Where they look for tools",

  // Contact rules
  contactNote: "What research found in the sources about contacting these buyers. It is not legal advice.",
  restricts: "Restricts this channel",
  restrictCountOne: "rule restricts this channel",
  restrictCountMany: "rules restrict this channel",
  channels: { email: "Email", linkedin: "LinkedIn", calls: "Calls" },
  whereLabel: "Where:",

  // Gaps and contradictions
  gapGroups: {
    ask: "Ask on the first call",
    conflict: "Conflicting evidence",
    careful: "Careful what you claim",
    verify: "Relay couldn't verify",
    unreadable: "Pages Relay couldn't read",
  },
  searched: "what Relay searched",

  // Sources
  showAllSources: "all",
  readOn: "Read",
} as const;
